### ISSUE TITLE
Make accessor naming consistent with fieldnames

### ISSUE THREAD

**Issue by nickrobinson251** [invenia/FullNetworkSystems.jl#23]
right now we have e.g. the accessor `get_regulation_commitment` to get the field `status_regulation` 

post #19 fieldnames are public API... so before relasing that we should decide if we want to change the fieldnames to more closely aligned with accessor names (we could change either/both, but accessors would need deprecations to be non-breaking)

(xref https://github.com/JuliaRegistries/General/pull/64688#issuecomment-1191580802)

**Comment by nickrobinson251** [comment]
Here are the accessor functions which (i) refer exactly to a field of some type and (ii) for which the accessor function refers to the data by a different name to the type 

i.e. where we you have to remember two names: the name when entering data, like `GeneratorTimeSeries(; asm_sup_on=...)`, and the name when retrieving data, like `get_supplemental_on(...)`.

i.e. these are the ones where i think we should consider aligning the names

| accessor `get_*` | fieldname | type |
|---|---|---|
| regulation_requirements | regulation | Zone |
| operating_reserve_requirements | operating_reserve | Zone |
| good_utility_requirements | good_utility | Zone |
| load | loads | System
| regmin | regulation_min | GeneratorTimeSeries |
| regmax | regulation_max | GeneratorTimeSeries |
| regulation | asm_regulation | GeneratorTimeSeries |
| spinning | asm_spin | GeneratorTimeSeries |
| supplemental_on | asm_sup_on | GeneratorTimeSeries |
| supplemental_off | asm_sup_off | GeneratorTimeSeries |
| commitment | status | GeneratorStatusRT |
| regulation_commitment | status_regulation |  GeneratorStatusRT |

**Comment by raphaelsaavedra** [comment]
Thanks for organising this!

My thoughts:

* We can change the field names in `Zone` to `regulation_requirement`, `operating_reserve_requirement` etc. This would still be slightly inconsistent with the accessor since the accessor name is plural (the accessor returns all requirements). I think that would be fine?
* Change `get_load` to `get_loads`
* Change `regmin` and `regmax` to `regulation_min/max` since it's clearer.
* For the ancillary offers, change both as they're both unclear. I vote for `*_offer` to make it clear that these are the offers.
* We can change `status` to `commitment` to match the accessor. The status name is a PowerSystems.jl relic.

**Comment by raphaelsaavedra** [comment]
On the topic of renaming, `system.lodf` should become `system.lodfs` and `get_lodf` should become `get_lodfs` since we store one LODF per contingency too.

**Comment by nickrobinson251** [comment]
Does this summarise the proposal (changes in **bold**):

| accessor `get_*` | fieldname | type |
|---|---|---|
| regulation_requirements | **regulation_requirement** | Zone |
| operating_reserve_requirements | **operating_reserve_requirement** | Zone |
| good_utility_requirements | **good_utility_requirement** | Zone |
| **loads** | loads | System
| **lodfs** | **lodfs** |  System |
| **regulation_min** | regulation_min | GeneratorTimeSeries |
| **regulation_max** | regulation_max | GeneratorTimeSeries |
| commitment | **commitment** | GeneratorStatusRT |
| regulation_commitment | **regulation_commitment** |  GeneratorStatusRT |

What are the proposals for the ancillary offers? Currently:
```
| accessor `get_*` | fieldname | type |
|---|---|---|
| regulation | asm_regulation | GeneratorTimeSeries |
| spinning | asm_spin | GeneratorTimeSeries |
| supplemental_on | asm_sup_on | GeneratorTimeSeries |
| supplemental_off | asm_sup_off | GeneratorTimeSeries |
```

**Comment by nickrobinson251** [comment]
another naming question (related to #25) why is it `increment/decrement` (single) rather than `increments/decrements` (plural) / should we change it?

**Comment by raphaelsaavedra** [comment]
Yes, that seems good to me!

My idea for the ancillary offers was 

Accessor: `get_regulation_offers`, fieldname: `regulation_offer`

>why is it increment/decrement (single) rather than increments/decrements (plural) / should we change it?

Good question, it can be either `increments` or `increment_bids`. The latter might be better for clarity

**Comment by nickrobinson251** [comment]
what about for spinning / sup_on / sup_off?

**Comment by raphaelsaavedra** [comment]
Same logic; `get_spinning_offers`, `spinning_offer`

`get_spinning_reserve_offers` might be clearer but too verbose imo, especially for the supplemental ones. For supplemental, the main question is what should we use as the name of the ancillary service (full name is "offline/online supplemental reserve"). `get_supplemental_on_offers` or `get_online_supplemental_offers` could work

**Comment by nickrobinson251** [comment]
okay, so having tried updating some code, long fieldnames (= long keywords) become really annoying 😆 how about:

| accessor `get_*` | fieldname | type |
|---|---|---|
| regulation_requirements | regulation | Zone |
| operating_reserve_requirements | operating_reserve | Zone |
| good_utility_requirements | good_utility | Zone |
| **loads** | loads | System
| **lodfs** | **lodfs** |  System |
| **regulation_min** | regulation_min | GeneratorTimeSeries |
| **regulation_max** | regulation_max | GeneratorTimeSeries |
| commitment | **commitment** | GeneratorStatusRT |
| regulation_commitment | **regulation_commitment** |  GeneratorStatusRT |
| **regulation_offers** | **regulation_offers** | GeneratorTimeSeries |
| **spinning_offers** | **spinning_offers** | GeneratorTimeSeries |
| **online_supplemental** | **online_supplemental** | GeneratorTimeSeries |
| **offline_supplemental** | **offline_supplemental** | GeneratorTimeSeries |

where we are trying to 
1. align accessor and fieldname/keyword (to minimise total names in the API and make it clear when two things are the same) 
2. be as explicit as possible e.g. `regulation_min` not `regmin` (to keep user code clear)
3. keep names as short as possible (again to keep user code clear, as overly verbose code can making code _harder_ to follow)

I realise now that one reason why accessor and fieldname can differ without it being confusing is because accessors always take a _System_, whereas fieldnames/keywords have the additional context of the constructor e.g. this is why i think `Zone(operating_reserve=...)` is fine and preferable than `Zone(operating_reserve_requirement=...)` which scored poorly on the "keep names short".

**Comment by raphaelsaavedra** [comment]
> I realise now that one reason why accessor and fieldname can differ without it being confusing is because accessors always take a System, whereas fieldnames/keywords have the additional context of the constructor e.g. this is why i think Zone(operating_reserve=...) is fine and preferable than Zone(operating_reserve_requirement=...) which scored poorly on the "keep names short".

Agree with this!

That all sounds good to me, I just think it would be confusing to have regulation and spinning as `_offers` but the supplemental ones not. Maybe `get_off_supplemental_offers` and `off_supplemental_offer` to avoid having really long names?

**Comment by nickrobinson251** [comment]
> it can be either `increments` or `increment_bids`. The latter might be better for clarity

if we had `increment_bids` and `decrement_bids` would we change the name of `price_sensitive_demand` ?

I think maybe just going to the plural (`increments`, `decrements`, `price_sensitive_demands`) might be better -- what do you think?

**Comment by raphaelsaavedra** [comment]
Plurals might be good to simplify!

Price sensitive demands are bids too, although they are not virtual... "price sensitive demands" just comes from the MISO documentation, but there's several names this could fall under, e.g. controllable loads (maybe @mjamei19 has some opinions over names here). But I'm fine with plurals

**Comment by nickrobinson251** [comment]
interesting! i don't _love_ that we use "demands" here, where elsewhere we use "loads" (and "decrements")

...but for now i'm inclined towards leaving as it is (unless someone favours the change)

**Comment by raphaelsaavedra** [comment]
Yeah I agree with that. If we do change to something along the lines of controllable loads or price-sensitive loads, we'd probably have to change `loads` to `fixed_loads`, to make it clear that those are not included

**Comment by nickrobinson251** [comment]
since this fieldname is about to become public API, now is the best time to rename it

I think the options are
1. `price_sensitive_demands` 
2. `price_sensitive_loads`
3. `controllable_loads`

having thought about it more, i think i favour renaming. Any preference between 2 and 3 (personally i'm inclined to go for 2)

https://github.com/invenia/FullNetworkSystems.jl/pull/26/commits/1f9da957137324103e4bc704fcaa63e1be0ada82

> we'd probably have to change `loads` to `fixed_loads`, to make it clear that those are not included

I'd be inclined to just keep it as `loads` and rely on documentation to make clear these are the fixed loads

**Comment by nickrobinson251** [comment]
okay, gone with `price_sensitive_loads` and had to rename `psds_per_bus` -> `psls_per_bus` to match -- i'll leave #26 open til Monday
